# Generated by Django 2.2 on 2019-04-24 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=250)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='photos/')),
            ],
        ),
    ]
